name: Build and Push Docker Image With Qemu

on:
  workflow_dispatch:
    inputs:
      tag_list:
        description: 'Comma-separated list of tags to apply to the image (e.g., latest,1.0,stable)'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/bake-action@v6
        env:
          VERSION_TAGS: ${{ inputs.tag_list }}
        with:
          push: true
          targets: |
            ci